# This file is a template, and might need editing before it works on your project.
# use docker image with latex preinstalled
# since there is no official latex image, use https://github.com/blang/latex-docker
# possible alternative: https://github.com/natlownes/docker-latex
image: registry.gitlab.com/islandoftex/images/texlive:latest

build:
  script:
    - latexmk -xelatex memoria_tfm.tex
  after_script:
    - cat memoria_tfm.log
  artifacts:
    paths:
      - memoria_tfm.pdf
